### ISSUE TITLE
Add S3 URI and Site for Download Template - Historic collections

### ISSUE THREAD

**Issue by csidenblad** [TNRIS/data.tnris.org-svelte#16]
Im looking to add the S3 location to the [data.tnris.org](https://data.tnris.org/collection?c=a6a703ba-df8b-4d1b-8d4c-ece8ae786505#4.89/31.32/-100.12) download template.

S3 site ex. - https://tnris-data-warehouse.s3.us-east-1.amazonaws.com/index.html?prefix=LCD/collection/
S3 URI ex. - s3://tnris-data-warehouse/LCD/collection/
S3 Key ex - stratmap-2010-1m-lee-leon-madison-milam/

To do this for historic collection i think we will need to field or table to the DB, to hold the key (dir) locations. Unfortunately the key and collection names are the same and you can not build the URL|URI from existing information within the collection. The key location will need to be manually added by myself or @mitchellryant 

Maybe adding it to the download template, under Metadata. Maybe collapsible too.

I think we can pull this information from the existing fields in Historic Collections. The folders were created from pulling agency, from_date, and collections name fields in the Historic Collections db and Acquiring Agencies table.

**Comment by L-Har** [comment]
Hey @ctrepka . I think we were putting this on hold until September to give Aaron time to name the folders in the data warehouse correctly. (They needed to match a certain pattern to match how we are buildingthe URL.
