### ISSUE TITLE
Historical Imagery USACE Collection Abbreviation

### ISSUE THREAD

**Issue by A-M-Pearce** [TNRIS/data.tnris.org-svelte#50]
I'd like to request the abbreviations for the following historical imagery collections be added to the front end to allow S3 URL public access through data.tnris.org:

 USACE-1985-AransasRiver
 USACE-1985-BaffinBay
 USACE-1985-DeWitt
 USACE-1985-DickinsonBayou
 USACE-1985-GCH
 USACE-1985-GIWW
 USACE-1985-Kleburg
 USACE-1985-LiveOak
 USACE-1985-MissionBay
 USACE-1985-OysterBayou
 USACE-1985-PortBolivar
 USACE-1985-SanAntonioRiver
 USACE-1985-TexasCityChannel
 USACE-1985-TrinityBayOLR
 USACE-1985-TrinityBayWalliceville
 USACE-1985-WGB

**Comment by mitchellryant** [comment]
I think they want `USACE` added to src/lib/Components/Collection/Metadata.svelte line #81.

but the older I get the less I know or understand.

good luck!
