### ISSUE TITLE
Change zip names and locations

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/data.tnris.org-svelte#51]
[src/lib/Components/Collection/Metadata/AboutLidar.svelte](https://github.com/TNRIS/data.tnris.org-svelte/blob/566f0e88896257a7330ee429bc2483b944d284cb/src/lib/Components/Collection/Metadata/AboutLidar.svelte#L19)
Line 19 - href="https://cdn.tnris.org/lidar-availability/tnris-lidar_48_vector.zip" to href="https://tnris-data-warehouse.s3.us-east-1.amazonaws.com/LCD/collection/lidar_availability/Availability-Index/txgio-lidar-index.zip"

[src/lib/Components/Collection/Metadata.svelte](https://github.com/TNRIS/data.tnris.org-svelte/blob/566f0e88896257a7330ee429bc2483b944d284cb/src/lib/Components/Collection/Metadata.svelte#L56)
line 153 - href="https://cdn.tnris.org/data/RESTful_Services/TNRIS_RESTful_Services.zip" to href="https://tnris-data-warehouse.s3.us-east-1.amazonaws.com/LCD/collection/txgio_restful_services/TxGIO_RESTful_Services.zip"

**Comment by L-Har** [comment]
Fixed #67
