### ISSUE TITLE
EPSG Codes on front end

### ISSUE THREAD

**Issue by mitchellryant** [TNRIS/data.tnris.org-svelte#56]
In 2018 when we designed the API DB, the Projections Look Up table was designed to be just the number for the EPSG Code. And on the front end we would add the web site https://epsg.io in front of the number and create an href to that site, ex https://epsg.io/3857. This would all the user to get the technical details of each CRS.

Currently we are just showing a number in this part of the front end. Not all user may know what these numbers mean.
![image](https://github.com/TNRIS/data.tnris.org-svelte/assets/8459928/c3a29881-082b-4083-8a72-23c430d24730)

If we no longer want to href out to EPSG.io, should we consider using a common name or abbreviation. This would require a model change.

**Comment by L-Har** [comment]
I don't have a problem referencing out to epsg.io

I'll look at how many different spatial references we use. I could add a new column then convert the codes over to a String Like WGS84 then swap out the columns in the model and do it in bulk. 

@ThorTheDestroyer @mitchellryant Those are two options. Let me know what you guys think.

I'm going to wait until @ctrepka @TWDBrob @twdbben and @DipakS28 get back to discuss it with them and see if it's used as a foreign key or something important though. first so it won't be done until next week.

**Comment by L-Har** [comment]
Completed in pull request #68 and #69 

Decided to go with "por que no los dos?" (Why not both?)

Human readable format is shown and it creates a hyperlink to epsg.io ex: [WGS84](https://epsg.io/4326)
